listen_addresses = '*'
max_connections = 50
shared_buffers = 128MB

# Matikan sementara logging ke file agar tidak Permission Denied
logging_collector = off

timezone = 'Asia/Jakarta'
log_timezone = 'Asia/Jakarta'
